### ISSUE TITLE
Build Error: Function invocation 'getCurrentActivity()' expected

### ISSUE THREAD

**Issue by edoko** [gronxb/hot-updater#513]
### Precheck

- [x] Infrastructure may have changed. Did you retry `hot-updater init`?
- [x] Is your Node version v20 or higher?
- [x] Are you aware that the update will only work properly if you `hot-updater deploy` after building the native app?

### Name, Version of hot-updater

0.19.9

### Version of react-native

0.81.0

### Platforms

Android

### Architecture

New Architecture(Fabric)

### What provider are you seeing the problem on? (multiple)

Firebase

### Expo App

- [ ] I am using Expo
- [ ] Project is managed with Expo [CNG](https://docs.expo.dev/workflow/continuous-native-generation/)(android, ios directories are included in `.gitignore`)

### Bundler

metro(hermes)

### What happened?

After updating from RN 0.80.2 to 0.81.0, an error occurs during build.
The error persists even after deleting the gradlew cache and restarting.

### Relevant log output

```shell
e: file:///xxx/node_modules/@hot-updater/react-native/android/src/newarch/HotUpdaterModule.kt:36:10 Function invocation 'getCurrentActivity()' expected.

warning: The following options were not recognized by any processor: '[dagger.hilt.internal.useAggregatingRootProcessor, dagger.fastInit, dagger.hilt.android.internal.disableAndroidSuperclassValidation, dagger.hilt.android.internal.projectType]'
1 warning FAILURE: Build completed with 2 failures. 1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hot-updater_react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gronxb** [comment]
Fixed in v0.20.0.

Thanks !
