### PR TITLE
feat(android): Supports RN 0.81.0

### LINKED ISSUE #512: Unresolved reference 'currentActivity'
### Precheck

- [x] Infrastructure may have changed. Did you retry `hot-updater init`?
- [x] Is your Node version v20 or higher?
- [x] Are you aware that the update will only work properly if you `hot-updater deploy` after building the native app?

### Name, Version of hot-updater

0.19.9

### Version of react-native

0.81.0

### Platforms

Android

### Architecture

Old Architecture(Bridge)

### What provider are you seeing the problem on? (multiple)

Cloudflare

### Expo App

- [ ] I am using Expo
- [ ] Project is managed with Expo [CNG](https://docs.expo.dev/workflow/continuous-native-generation/)(android, ios directories are included in `.gitignore`)

### Bundler

metro

### What happened?

I am getting this error on React Native 81.0 version.

Unresolved reference 'currentActivity'

@gronxb 

### Relevant log output

```shell

```

### Reproducible Sample Repository

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #513: Build Error: Function invocation 'getCurrentActivity()' expected
### Precheck

- [x] Infrastructure may have changed. Did you retry `hot-updater init`?
- [x] Is your Node version v20 or higher?
- [x] Are you aware that the update will only work properly if you `hot-updater deploy` after building the native app?

### Name, Version of hot-updater

0.19.9

### Version of react-native

0.81.0

### Platforms

Android

### Architecture

New Architecture(Fabric)

### What provider are you seeing the problem on? (multiple)

Firebase

### Expo App

- [ ] I am using Expo
- [ ] Project is managed with Expo [CNG](https://docs.expo.dev/workflow/continuous-native-generation/)(android, ios directories are included in `.gitignore`)

### Bundler

metro(hermes)

### What happened?

After updating from RN 0.80.2 to 0.81.0, an error occurs during build.
The error persists even after deleting the gradlew cache and restarting.

### Relevant log output

```shell
e: file:///xxx/node_modules/@hot-updater/react-native/android/src/newarch/HotUpdaterModule.kt:36:10 Function invocation 'getCurrentActivity()' expected.

warning: The following options were not recognized by any processor: '[dagger.hilt.internal.useAggregatingRootProcessor, dagger.fastInit, dagger.hilt.android.internal.disableAndroidSuperclassValidation, dagger.hilt.android.internal.projectType]'
1 warning FAILURE: Build completed with 2 failures. 1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hot-updater_react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org
```

### Reproducible Sample Repository

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gronxb**
Fixed #513 
Fixed #512

### CODE REVIEW

**Comment by gronxb** [comment]
https://github.com/facebook/react-native/pull/51017/files#diff-ba32120fa9c92ad015bce2c61200c6a934d876231d3cadd666b6c7006ab4b0a9L111

* as-is

image

* to-be

image



changes mReactHostDelegate

File: packages/react-native/android/src/newarch/HotUpdaterModule.kt [hunk 1]
```diff
@@ -27,13 +25,11 @@ class HotUpdaterModule internal constructor(
...
     }
 
-    @ReactMethod
     override fun updateBundle(
         params: ReadableMap,
         promise: Promise,
     ) {
-        // Use lifecycleScope when currentActivity is FragmentActivity
-        (currentActivity as? FragmentActivity)?.lifecycleScope?.launch {
+        (mReactApplicationContext.currentActivity as FragmentActivity?)?.lifecycleScope?.launch {
```
Comment (gronxb) [inline packages/react-native/android/src/newarch/HotUpdaterModule.kt:32]: core

File: packages/react-native/android/src/newarch/ReactIntegrationManager.kt [hunk 2]
```diff
@@ -17,7 +17,19 @@ class ReactIntegrationManager(
...
+            val reactHostDelegateField =
+                try {
+                    reactHost::class.java.getDeclaredField("mReactHostDelegate")
+                } catch (e: NoSuchFieldException) {
+                    try {
+                        reactHost::class.java.getDeclaredField("reactHostDelegate")
+                    } catch (e2: NoSuchFieldException) {
+                        throw RuntimeException("Neither mReactHostDelegate nor reactHostDelegate field found", e2)
+                    }
+                }
```
Comment (gronxb) [inline packages/react-native/android/src/newarch/ReactIntegrationManager.kt:31]: core

File: packages/react-native/android/proguard-rules.pro [hunk 3]
```diff
@@ -6,8 +6,10 @@
 
 # New Architecture
 # Keep fields accessed via reflection in ReactHost
+# Support both Java (mReactHostDelegate) and Kotlin (reactHostDelegate) field names
 -keepclassmembers class com.facebook.react.runtime.ReactHostImpl {
     private final ** mReactHostDelegate;
+    private val reactHostDelegate: **;
 }
```
Comment (gronxb) [inline packages/react-native/android/proguard-rules.pro:13]: core
