### ISSUE TITLE
Vulnerable dependency commons-compress 1.24.0

### ISSUE THREAD

**Issue by tiagohs** [gronxb/hot-updater#628]
### Precheck

- [x] Infrastructure may have changed. Did you retry `hot-updater init`?
- [x] Is your Node version v20 or higher?
- [x] Are you aware that the update will only work properly if you `hot-updater deploy` after building the native app?

### Name, Version of hot-updater

0.21.1

### Version of react-native

0.81.5

### Platforms

Android, iOS

### Architecture

New Architecture(Fabric)

### What provider are you seeing the problem on? (multiple)

S3 & Lambda

### Expo App

- [ ] I am using Expo
- [ ] Project is managed with Expo [CNG](https://docs.expo.dev/workflow/continuous-native-generation/)(android, ios directories are included in `.gitignore`)

### Bundler

metro(hermes)

### What happened?

I am having issues building for Android after updating the library. It seems to be a problem related to org.apache.commons:commons-compress:1.24.0, which was included in the latest version.

```
project :app > project :hot-updater_react-native
      > Cannot find a version of 'org.apache.commons:commons-compress' that satisfies the version constraints:
.
.
Dependency path 'com.recarga.android:app:unspecified' --> 'com.discover.sdk:card-reader:TOOK2.3.2-releaseCandidate' (runtime) --> 'org.apache.commons:commons-compress:{strictly 1.20}' because of the following reason: Fixed security issues: CVE-2018-11771
```

I tried manually changing the version to 1.28.0 and still, the error persists."

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.apache.commons:commons-compress:1.24.0.
     Required by:
         project :app > project :hot-updater_react-native
      > Cannot find a version of 'org.apache.commons:commons-compress' that satisfies the version constraints:
           Dependency path 'com.recarga.android:app:unspecified' --> 'com.android:hot-updater_react-native:unspecified' (debugRuntimeElements) --> 'org.apache.commons:commons-compress:1.24.0'
           Dependency path 'com.android:app:unspecified' --> 'com.discover.sdk:core:COR1.1.4-releaseCandidate' (runtime) --> 'org.apache.commons:commons-compress:{strictly 1.20}' because of the following reason: Fixed security issues: CVE-2018-11771
           Dependency path 'com.android:app:unspecified' --> 'com.discover.sdk:card-reader:TOOK2.3.2-releaseCandidate' (runtime) --> 'org.apache.commons:commons-compress:{strictly 1.20}' because of the following reason: Fixed security issues: CVE-2018-11771
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gronxb** [comment]
What version of Gradle are you using?

**Comment by tiagohs** [comment]
Wrapper version : gradle-8.14.3-bin.

I saw that version 1.24.0 on [MVN](https://mvnrepository.com/artifact/org.apache.commons/commons-compress) (or Maven) has vulnerabilities.

**Comment by gronxb** [comment]
I downgraded the version to support up to RN 0.72, but I’ll look into it 😓 Thanks

**Comment by gronxb** [comment]
In your case, does it work well if you update the commons-compress version to the latest 1.28.0? (Can you check with a patch?)

**Comment by tiagohs** [comment]
No, strangely enough, it still fails for me here when I use version 1.28.0.

```
Could not resolve org.apache.commons:commons-compress:1.28.0.
     Required by:
         project :app > project :hot-updater_react-native
      > Cannot find a version of 'org.apache.commons:commons-compress' that satisfies the version constraints:
           Dependency path 'com.android:app:unspecified' --> 'com.android:hot-updater_react-native:unspecified' (debugRuntimeElements) --> 'org.apache.commons:commons-compress:1.28.0'
           Dependency path 'com.android:app:unspecified' --> 'com.discover.sdk:core:COR1.1.4-releaseCandidate' (runtime) --> 'org.apache.commons:commons-compress:{strictly 1.20}' because of the following reason: Fixed security issues: CVE-2018-11771
           Dependency path 'com.android:app:unspecified' --> 'com.discover.sdk:card-reader:TOOK2.3.2-releaseCandidate' (runtime) --> 'org.apache.commons:commons-compress:{strictly 1.20}' because of the following reason: Fixed security issues: CVE-2018-11771
```

Could you test a build there with 1.28.0 to confirm that it works?

**Comment by gronxb** [comment]
It worked on RN 0.81 with version 1.28.0, but failed on RN 0.72.
So I used version 1.24.0 to support up to RN 0.72.

However, due to several potential security issues in that library, I’m going to look into other libraries as well.

**Comment by gronxb** [comment]
Could you add this code your build.gradle ?

```gradle
configurations.all {
    resolutionStrategy {
        force 'org.apache.commons:commons-compress:1.20'
    }
}
```

It looks like the com.discover.sdk library in your project has strictly pinned that dependency to version 1.20.0.

**Comment by tiagohs** [comment]
Yes, it worked! Thank you :)"

"Will it be necessary to bump the version up slightly? According to MVN, version `1.24` has vulnerability issues.

**Comment by gronxb** [comment]
I’m trying to find the optimal version.

**Comment by tiagohs** [comment]
I think that only change to 0.28.0 dont work very well :'(

```
java.lang.NoSuchMethodError: No virtual method getNextEntry()Lorg/apache/commons/compress/archivers/tar/TarArchiveEntry; in class Lorg/apache/commons/compress/archivers/tar/TarArchiveInputStream; or its super classes (declaration of 'org.apache.commons.compress.archivers.tar.TarArchiveInputStream' appears in /data/app/~~SSm8bK1oLKuJtVfzgRiUJA==/com.recarga.recarga-vUFPBDXxh1aM5VTgHFQetg==/base.apk!classes38.dex)
                                                                                                    	at com.hotupdater.TarBrDecompressionStrategy.decompress(TarBrDecompressionStrategy.kt:60)
                                                                                                    	at com.hotupdater.DecompressService.extractZipFile(DecompressService.kt:46)
                                                                                                    	at com.hotupdater.BundleFileStorageService$updateBundle$2.invokeSuspend(BundleFileStorageService.kt:208)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e691da0, Dispatchers.Main.immediate]
```

The error occurs when trying to use the `BrotliCompressorInputStream` and `TarArchiveInputStream` classes.

**Comment by gronxb** [comment]
Ah, it says that version 1.20.0 doesn’t have getNextEntry. I guess it disappeared when the version was fixed. Can you try locking it to 1.28.0?

```gradle
configurations.all {
        resolutionStrategy {
            force 'org.apache.commons:commons-compress:1.28.0'
        }
    }
```

**Comment by tiagohs** [comment]
Yes! Use 1.28.0 resolved this issue, thanks :)
